### ISSUE TITLE
create config file

### ISSUE THREAD

**Issue by P0nt14c** [RITRedteam/bruhdotzip#2]
Add functionality to BruhDotZip by creating a config file alternative. 
The tool would read the config and substitute in the variables to the program at run time
Variables could be assigned in the config or via the command line. 
Additionally, you can add an option -c/-configFile for the config file, which allows you to build multiple, separate configs for linux and windows

**Comment by mav8557** [comment]
Viper is a great library for this.

**Comment by d3adzo** [comment]
#7 working on it here
